/* text.h

   Copyright 2023 Natxo Malphas 
      
   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.  */

#ifndef TEXT_H
#define TEXT_H

static const int TAB_LEN = 8;
static const int CICERO_WORDS = 4077;
static const int OG_LOR_WORDS = 69;
static const int OG_LOR_MIN_WORDS = 5;
static const char *TAB = "\t";
static const char *NEW_LINE = "\n";

char *gen_text (int paragraphs, long classic_mode, _Bool line_format,
                _Bool indent, int min_wps, int max_wps, int min_wpp,
                int max_wpp, int max_cpl);

static const char *OG_LOREM[69] = { "Lorem", "ipsum", "dolor", "sit", "amet,",
  "consectetur", "adipiscing", "elit,", "sed", "do", "eiusmod", "tempor",
  "incididunt", "ut", "labore", "et", "dolore", "magna", "aliqua.", "Ut",
  "enim", "ad", "minim", "veniam,", "quis", "nostrud", "exercitation",
  "ullamco", "laboris", "nisi", "ut", "aliquip", "ex", "ea", "commodo",
  "consequat.", "Duis", "aute", "irure", "dolor", "in", "reprehenderit",
  "in", "voluptate", "velit", "esse", "cillum", "dolore", "eu", "fugiat",
  "nulla", "pariatur.", "Excepteur", "sint", "occaecat", "cupidatat", "non",
  "proident,", "sunt", "in", "culpa", "qui", "officia", "deserunt", "mollit",
  "anim", "id", "est", "laborum."
};

static char *OG_LOREM_MIN[5] = { "Lorem", "ipsum", "dolor", "sit", "amet," };

static const char *DE_FINIBUS[4077] =
  { "sed", "ut", "perspiciatis,", "unde", "omnis",
  "iste", "natus", "error", "sit", "voluptatem", "accusantium",
  "doloremque", "laudantium,", "totam", "rem", "aperiam", "eaque",
  "ipsa,", "quae", "ab", "illo", "inventore", "veritatis", "et", "quasi",
  "architecto", "beatae", "vitae", "dicta", "sunt,", "explicabo",
  "nemo", "enim", "ipsam", "voluptatem,", "quia", "voluptas", "sit,",
  "aspernatur", "aut", "odit", "aut", "fugit,", "sed", "quia",
  "consequuntur", "magni", "dolores", "eos,", "qui", "ratione",
  "voluptatem", "sequi", "nesciunt,", "neque", "porro", "quisquam",
  "est,", "qui", "dolorem", "ipsum,", "quia", "dolor", "sit,", "amet,",
  "consectetur,", "adipisci", "velit,", "sed", "quia", "non", "numquam",
  "eius", "modi", "tempora", "incidunt,", "ut", "labore", "et", "dolore",
  "magnam", "aliquam", "quaerat", "voluptatem", "ut", "enim", "ad",
  "minima", "veniam,", "quis", "nostrum", "exercitationem", "ullam",
  "corporis", "suscipit", "laboriosam,", "nisi", "ut", "aliquid", "ex",
  "ea", "commodi", "consequatur?", "quis", "autem", "vel", "eum", "iure",
  "reprehenderit,", "qui", "in", "ea", "voluptate", "velit", "esse,",
  "quam", "nihil", "molestiae", "consequatur,", "vel", "illum,", "qui",
  "dolorem", "eum", "fugiat,", "quo", "voluptas", "nulla", "pariatur?",
  "at", "vero", "eos", "et", "accusamus", "et", "iusto", "odio",
  "dignissimos", "ducimus,", "qui", "blanditiis", "praesentium",
  "voluptatum", "deleniti", "atque", "corrupti,", "quos", "dolores",
  "et", "quas", "molestias", "excepturi", "sint,", "obcaecati",
  "cupiditate", "non", "provident,", "similique", "sunt", "in", "culpa,",
  "qui", "officia", "deserunt", "mollitia", "animi,", "id", "est",
  "laborum", "et", "dolorum", "fuga", "et", "harum", "quidem", "rerum",
  "facilis", "est", "et", "expedita", "distinctio", "nam", "libero",
  "tempore,", "cum", "soluta", "nobis", "est", "eligendi", "optio,",
  "cumque", "nihil", "impedit,", "quo", "minus", "id,", "quod", "maxime",
  "placeat,", "facere", "possimus,", "omnis", "voluptas", "assumenda",
  "est,", "omnis", "dolor", "repellendus", "temporibus", "autem",
  "quibusdam", "et", "aut", "officiis", "debitis", "aut", "rerum",
  "necessitatibus", "saepe", "eveniet,", "ut", "et", "voluptates",
  "repudiandae", "sint", "et", "molestiae", "non", "recusandae",
  "itaque", "earum", "rerum", "hic", "tenetur", "a", "sapiente",
  "delectus,", "ut", "aut", "reiciendis", "voluptatibus", "maiores",
  "alias", "consequatur", "aut", "perferendis", "doloribus",
  "asperiores", "repellat", "hanc", "ego", "cum", "teneam",
  "sententiam,", "quid", "est", "cur", "verear,", "ne", "ad", "eam",
  "non", "possim", "accommodare", "torquatos", "nostros?", "quos", "tu",
  "paulo", "ante", "cum", "memoriter,", "tum", "etiam", "erga", "nos",
  "amice", "et", "benivole", "collegisti,", "nec", "me", "tamen",
  "laudandis", "maioribus", "meis", "corrupisti", "nec", "segniorem",
  "ad", "respondendum", "reddidisti", "quorum", "facta", "quem", "ad",
  "modum,", "quaeso,", "interpretaris?", "sicine", "eos", "censes",
  "aut", "in", "armatum", "hostem", "impetum", "fecisse", "aut", "in",
  "liberos", "atque", "in", "sanguinem", "suum", "tam", "crudelis",
  "fuisse,", "nihil", "ut", "de", "utilitatibus,", "nihil", "ut", "de",
  "commodis", "suis", "cogitarent?", "at", "id", "ne", "ferae", "quidem",
  "faciunt,", "ut", "ita", "ruant", "itaque", "turbent,", "ut", "earum",
  "motus", "et", "impetus", "quo", "pertineant", "non", "intellegamus,",
  "tu", "tam", "egregios", "viros", "censes", "tantas", "res",
  "gessisse", "sine", "causa?", "quae", "fuerit", "causa,", "mox",
  "videro;", "interea", "hoc", "tenebo,", "si", "ob", "aliquam",
  "causam", "ista,", "quae", "sine", "dubio", "praeclara", "sunt,",
  "fecerint,", "virtutem", "iis", "per", "se", "ipsam", "causam", "non",
  "fuisse", "torquem", "detraxit", "hosti", "et", "quidem",
  "se", "texit,", "ne", "interiret", "at", "magnum", "periculum",
  "adiit", "in", "oculis", "quidem", "exercitus", "quid",
  "ex", "eo", "est", "consecutus?", "laudem", "et", "caritatem,",
  "quae", "sunt", "vitae", "sine", "metu", "degendae", "praesidia",
  "firmissima", "filium", "morte", "multavit", "si",
  "sine", "causa,", "nollem", "me", "ab", "eo", "ortum,", "tam",
  "inportuno", "tamque", "crudeli;", "sin,", "ut", "dolore", "suo",
  "sanciret", "militaris", "imperii", "disciplinam", "exercitumque",
  "in", "gravissimo", "bello", "animadversionis", "metu", "contineret,",
  "saluti", "prospexit", "civium,", "qua", "intellegebat", "contineri",
  "suam", "atque", "haec", "ratio", "late", "patet", "in", "quo",
  "enim", "maxime", "consuevit", "iactare", "vestra", "se", "oratio,",
  "tua", "praesertim,", "qui", "studiose", "antiqua", "persequeris,",
  "claris", "et", "fortibus", "viris", "commemorandis", "eorumque",
  "factis", "non", "emolumento", "aliquo,", "sed", "ipsius",
  "honestatis", "decore", "laudandis,", "id", "totum", "evertitur", "eo",
  "delectu", "rerum,", "quem", "modo", "dixi,", "constituto,", "ut",
  "aut", "voluptates", "omittantur", "maiorum", "voluptatum",
  "adipiscendarum", "causa", "aut", "dolores", "suscipiantur", "maiorum",
  "dolorum", "effugiendorum", "gratia", "sed", "de", "clarorum",
  "hominum", "factis", "illustribus", "et", "gloriosis", "satis", "hoc",
  "loco", "dictum", "sit", "erit", "enim", "iam", "de", "omnium",
  "virtutum", "cursu", "ad", "voluptatem", "proprius", "disserendi",
  "locus", "nunc", "autem", "explicabo,", "voluptas", "ipsa", "quae",
  "qualisque", "sit,", "ut", "tollatur", "error", "omnis", "imperitorum",
  "intellegaturque", "ea,", "quae", "voluptaria,", "delicata,", "mollis",
  "habeatur", "disciplina,", "quam", "gravis,", "quam", "continens,",
  "quam", "severa", "sit", "non", "enim", "hanc", "solam", "sequimur,",
  "quae", "suavitate", "aliqua", "naturam", "ipsam", "movet", "et",
  "cum", "iucunditate", "quadam", "percipitur", "sensibus,", "sed",
  "maximam", "voluptatem", "illam", "habemus,", "quae", "percipitur",
  "omni", "dolore", "detracto,", "nam", "quoniam,", "cum", "privamur",
  "dolore,", "ipsa", "liberatione", "et", "vacuitate", "omnis",
  "molestiae", "gaudemus,", "omne", "autem", "id,", "quo", "gaudemus,",
  "voluptas", "est,", "ut", "omne,", "quo", "offendimur,", "dolor,",
  "doloris", "omnis", "privatio", "recte", "nominata", "est",
  "voluptas", "ut", "enim,", "cum", "cibo", "et", "potione", "fames",
  "sitisque", "depulsa", "est,", "ipsa", "detractio", "molestiae",
  "consecutionem", "affert", "voluptatis,", "sic", "in", "omni", "re",
  "doloris", "amotio", "successionem", "efficit", "voluptatis",
  "itaque", "non", "placuit", "epicuro", "medium", "esse", "quiddam",
  "inter", "dolorem", "et", "voluptatem;", "illud", "enim", "ipsum,",
  "quod", "quibusdam", "medium", "videretur,", "cum", "omni", "dolore",
  "careret,", "non", "modo", "voluptatem", "esse,", "verum", "etiam",
  "summam", "voluptatem", "quisquis", "enim", "sentit,", "quem", "ad",
  "modum", "sit", "affectus,", "eum", "necesse", "est", "aut", "in",
  "voluptate", "esse", "aut", "in", "dolore", "omnis", "autem",
  "privatione", "doloris", "putat", "epicurus", "terminari", "summam",
  "voluptatem,", "ut", "postea", "variari", "voluptas", "distinguique",
  "possit,", "augeri", "amplificarique", "non", "possit", "at", "etiam",
  "athenis,", "ut", "e", "patre", "audiebam", "facete", "et", "urbane",
  "stoicos", "irridente,", "statua", "est", "in", "ceramico",
  "chrysippi", "sedentis", "porrecta", "manu,", "quae", "manus",
  "significet", "illum", "in", "hae", "esse", "rogatiuncula",
  "delectatum:", "'numquidnam", "manus", "tua", "sic", "affecta,",
  "quem", "ad", "modum", "affecta", "nunc", "est,", "desiderat?'",
  "nihil", "sane", "'at,", "si", "voluptas", "esset", "bonum,",
  "desideraret'", "ita", "credo", "'non", "est", "igitur",
  "voluptas", "bonum'", "hoc", "ne", "statuam", "quidem", "dicturam",
  "pater", "aiebat,", "si", "loqui", "posset", "conclusum", "est",
  "enim", "contra", "cyrenaicos", "satis", "acute,", "nihil", "ad",
  "epicurum", "nam", "si", "ea", "sola", "voluptas", "esset,", "quae",
  "quasi", "titillaret", "sensus,", "ut", "ita", "dicam,", "et", "ad",
  "eos", "cum", "suavitate", "afflueret", "et", "illaberetur,", "nec",
  "manus", "esse", "contenta", "posset", "nec", "ulla", "pars",
  "vacuitate", "doloris", "sine", "iucundo", "motu", "voluptatis",
  "sin", "autem", "summa", "voluptas", "est,", "ut", "epicuro",
  "placet,", "nihil", "dolere,", "primum", "tibi", "recte,",
  "chrysippe,", "concessum", "est", "nihil", "desiderare", "manum,",
  "cum", "ita", "esset", "affecta,", "secundum", "non", "recte,", "si",
  "voluptas", "esset", "bonum,", "fuisse", "desideraturam", "idcirco",
  "enim", "non", "desideraret,", "quia,", "quod", "dolore", "caret,",
  "id", "in", "voluptate", "est", "extremum", "autem", "esse",
  "bonorum", "voluptatem", "ex", "hoc", "facillime", "perspici",
  "potest:", "constituamus", "aliquem", "magnis,", "multis,",
  "perpetuis", "fruentem", "et", "animo", "et", "corpore",
  "voluptatibus", "nullo", "dolore", "nec", "impediente", "nec",
  "inpendente,", "quem", "tandem", "hoc", "statu", "praestabiliorem",
  "aut", "magis", "expetendum", "possimus", "dicere?", "inesse", "enim",
  "necesse", "est", "in", "eo,", "qui", "ita", "sit", "affectus,", "et",
  "firmitatem", "animi", "nec", "mortem", "nec", "dolorem", "timentis,",
  "quod", "mors", "sensu", "careat,", "dolor", "in", "longinquitate",
  "levis,", "in", "gravitate", "brevis", "soleat", "esse,", "ut", "eius",
  "magnitudinem", "celeritas,", "diuturnitatem", "allevatio",
  "consoletur", "ad", "ea", "cum", "accedit,", "ut", "neque", "divinum",
  "numen", "horreat", "nec", "praeteritas", "voluptates", "effluere",
  "patiatur", "earumque", "assidua", "recordatione", "laetetur,", "quid",
  "est,", "quod", "huc", "possit,", "quod", "melius", "sit,",
  "accedere?", "statue", "contra", "aliquem", "confectum", "tantis",
  "animi", "corporisque", "doloribus,", "quanti", "in", "hominem",
  "maximi", "cadere", "possunt,", "nulla", "spe", "proposita", "fore",
  "levius", "aliquando,", "nulla", "praeterea", "neque", "praesenti",
  "nec", "expectata", "voluptate,", "quid", "eo", "miserius", "dici",
  "aut", "fingi", "potest?", "quodsi", "vita", "doloribus", "referta",
  "maxime", "fugienda", "est,", "summum", "profecto", "malum", "est",
  "vivere", "cum", "dolore,", "cui", "sententiae", "consentaneum", "est",
  "ultimum", "esse", "bonorum", "eum", "voluptate", "vivere", "nec",
  "enim", "habet", "nostra", "mens", "quicquam,", "ubi", "consistat",
  "tamquam", "in", "extremo,", "omnesque", "et", "metus", "et",
  "aegritudines", "ad", "dolorem", "referuntur,", "nec", "praeterea",
  "est", "res", "ulla,", "quae", "sua", "natura", "aut", "sollicitare",
  "possit", "aut", "angere", "praeterea", "et", "appetendi", "et",
  "refugiendi", "et", "omnino", "rerum", "gerendarum", "initia",
  "proficiscuntur", "aut", "a", "voluptate", "aut", "a", "dolore",
  "quod", "cum", "ita", "sit,", "perspicuum", "est", "omnis", "rectas",
  "res", "atque", "laudabilis", "eo", "referri,", "ut", "cum",
  "voluptate", "vivatur", "quoniam", "autem", "id", "est", "vel",
  "summum", "bonorum", "vel", "ultimum", "vel", "extremum", "quod",
  "graeci", "telos", "nominant", "quod", "ipsum", "nullam", "ad",
  "aliam", "rem,", "ad", "id", "autem", "res", "referuntur", "omnes,",
  "fatendum", "est", "summum", "esse", "bonum", "iucunde", "vivere",
  "id", "qui", "in", "una", "virtute", "ponunt", "et", "splendore",
  "nominis", "capti", "quid", "natura", "postulet", "non",
  "intellegunt,", "errore", "maximo,", "si", "epicurum", "audire",
  "voluerint,", "liberabuntur:", "istae", "enim", "vestrae", "eximiae",
  "pulchraeque", "virtutes", "nisi", "voluptatem", "efficerent,", "quis",
  "eas", "aut", "laudabilis", "aut", "expetendas", "arbitraretur?", "ut",
  "enim", "medicorum", "scientiam", "non", "ipsius", "artis,", "sed",
  "bonae", "valetudinis", "causa", "probamus,", "et", "gubernatoris",
  "ars,", "quia", "bene", "navigandi", "rationem", "habet,",
  "utilitate,", "non", "arte", "laudatur,", "sic", "sapientia,", "quae",
  "ars", "vivendi", "putanda", "est,", "non", "expeteretur,", "si",
  "nihil", "efficeret;", "nunc", "expetitur,", "quod", "est", "tamquam",
  "artifex", "conquirendae", "et", "comparandae", "voluptatis",
  "quam", "autem", "ego", "dicam", "voluptatem,", "iam", "videtis,",
  "ne", "invidia", "verbi", "labefactetur", "oratio", "mea",
  "nam", "cum", "ignoratione", "rerum", "bonarum", "et", "malarum",
  "maxime", "hominum", "vita", "vexetur,", "ob", "eumque", "errorem",
  "et", "voluptatibus", "maximis", "saepe", "priventur", "et",
  "durissimis", "animi", "doloribus", "torqueantur,", "sapientia", "est",
  "adhibenda,", "quae", "et", "terroribus", "cupiditatibusque",
  "detractis", "et", "omnium", "falsarum", "opinionum", "temeritate",
  "derepta", "certissimam", "se", "nobis", "ducem", "praebeat", "ad",
  "voluptatem", "sapientia", "enim", "est", "una,", "quae",
  "maestitiam", "pellat", "ex", "animis,", "quae", "nos", "exhorrescere",
  "metu", "non", "sinat", "qua", "praeceptrice", "in", "tranquillitate",
  "vivi", "potest", "omnium", "cupiditatum", "ardore", "restincto",
  "cupiditates", "enim", "sunt", "insatiabiles,", "quae", "non", "modo",
  "singulos", "homines,", "sed", "universas", "familias", "evertunt,",
  "totam", "etiam", "labefactant", "saepe", "rem", "publicam", "ex",
  "cupiditatibus", "odia,", "discidia,", "discordiae,", "seditiones,",
  "bella", "nascuntur,", "nec", "eae", "se", "foris", "solum", "iactant",
  "nec", "tantum", "in", "alios", "caeco", "impetu", "incurrunt,", "sed",
  "intus", "etiam", "in", "animis", "inclusae", "inter", "se",
  "dissident", "atque", "discordant,", "ex", "quo", "vitam",
  "amarissimam", "necesse", "est", "effici,", "ut", "sapiens", "solum",
  "amputata", "circumcisaque", "inanitate", "omni", "et", "errore",
  "naturae", "finibus", "contentus", "sine", "aegritudine", "possit",
  "et", "sine", "metu", "vivere", "quae", "est", "enim", "aut",
  "utilior", "aut", "ad", "bene", "vivendum", "aptior", "partitio",
  "quam", "illa,", "qua", "est", "usus", "epicurus?", "qui", "unum",
  "genus", "posuit", "earum", "cupiditatum,", "quae", "essent", "et",
  "naturales", "et", "necessariae,", "alterum,", "quae", "naturales",
  "essent", "nec", "tamen", "necessariae,", "tertium,", "quae", "nec",
  "naturales", "nec", "necessariae", "quarum", "ea", "ratio", "est,",
  "ut", "necessariae", "nec", "opera", "multa", "nec", "impensa",
  "expleantur;", "ne", "naturales", "quidem", "multa", "desiderant,",
  "propterea", "quod", "ipsa", "natura", "divitias,", "quibus",
  "contenta", "sit,", "et", "parabilis", "et", "terminatas", "habet;",
  "inanium", "autem", "cupiditatum", "nec", "modus", "ullus", "nec",
  "finis", "inveniri", "potest", "quodsi", "vitam", "omnem",
  "perturbari", "videmus", "errore", "et", "inscientia,",
  "sapientiamque", "esse", "solam,", "quae", "nos", "a", "libidinum",
  "impetu", "et", "a", "formidinum", "terrore", "vindicet", "et",
  "ipsius", "fortunae", "modice", "ferre", "doceat", "iniurias", "et",
  "omnis", "monstret", "vias,", "quae", "ad", "quietem", "et", "ad",
  "tranquillitatem", "ferant,", "quid", "est", "cur", "dubitemus",
  "dicere", "et", "sapientiam", "propter", "voluptates", "expetendam",
  "et", "insipientiam", "propter", "molestias", "esse", "fugiendam?",
  "eademque", "ratione", "ne", "temperantiam", "quidem", "propter", "se",
  "expetendam", "esse", "dicemus,", "sed", "quia", "pacem", "animis",
  "afferat", "et", "eos", "quasi", "concordia", "quadam", "placet", "ac",
  "leniat", "temperantia", "est", "enim,", "quae", "in", "rebus", "aut",
  "expetendis", "aut", "fugiendis", "ut", "rationem", "sequamur",
  "monet", "nec", "enim", "satis", "est", "iudicare", "quid",
  "faciendum", "non", "faciendumve", "sit,", "sed", "stare", "etiam",
  "oportet", "in", "eo,", "quod", "sit", "iudicatum", "plerique",
  "autem,", "quod", "tenere", "atque", "servare", "id,", "quod", "ipsi",
  "statuerunt,", "non", "possunt,", "victi", "et", "debilitati",
  "obiecta", "specie", "voluptatis", "tradunt", "se", "libidinibus",
  "constringendos", "nec", "quid", "eventurum", "sit", "provident", "ob",
  "eamque", "causam", "propter", "voluptatem", "et", "parvam", "et",
  "non", "necessariam", "et", "quae", "vel", "aliter", "pararetur", "et",
  "qua", "etiam", "carere", "possent", "sine", "dolore", "tum", "in",
  "morbos", "gravis,", "tum", "in", "damna,", "tum", "in", "dedecora",
  "incurrunt,", "saepe", "etiam", "legum", "iudiciorumque", "poenis",
  "obligantur", "qui", "autem", "ita", "frui", "volunt",
  "voluptatibus,", "ut", "nulli", "propter", "eas", "consequantur",
  "dolores,", "et", "qui", "suum", "iudicium", "retinent,", "ne",
  "voluptate", "victi", "faciant", "id,", "quod", "sentiant", "non",
  "esse", "faciendum,", "ii", "voluptatem", "maximam", "adipiscuntur",
  "praetermittenda", "voluptate", "idem", "etiam", "dolorem", "saepe",
  "perpetiuntur,", "ne,", "si", "id", "non", "faciant,", "incidant",
  "in", "maiorem", "ex", "quo", "intellegitur", "nec", "intemperantiam",
  "propter", "se", "esse", "fugiendam", "temperantiamque", "expetendam,",
  "non", "quia", "voluptates", "fugiat,", "sed", "quia", "maiores",
  "consequatur", "eadem", "fortitudinis", "ratio", "reperietur", "nam",
  "neque", "laborum", "perfunctio", "neque", "perpessio", "dolorum",
  "per", "se", "ipsa", "allicit", "nec", "patientia", "nec",
  "assiduitas", "nec", "vigiliae", "nec", "ea", "ipsa,", "quae",
  "laudatur,", "industria,", "ne", "fortitudo", "quidem,", "sed", "ista",
  "sequimur,", "ut", "sine", "cura", "metuque", "vivamus", "animumque",
  "et", "corpus,", "quantum", "efficere", "possimus,", "molestia",
  "liberemus", "ut", "enim", "mortis", "metu", "omnis", "quietae",
  "vitae", "status", "perturbatur,", "et", "ut", "succumbere",
  "doloribus", "eosque", "humili", "animo", "inbecilloque", "ferre",
  "miserum", "est,", "ob", "eamque", "debilitatem", "animi", "multi",
  "parentes,", "multi", "amicos,", "non", "nulli", "patriam,",
  "plerique", "autem", "se", "ipsos", "penitus", "perdiderunt,", "sic",
  "robustus", "animus", "et", "excelsus", "omni", "est", "liber", "cura",
  "et", "angore,", "cum", "et", "mortem", "contemnit,", "qua", "qui",
  "affecti", "sunt", "in", "eadem", "causa", "sunt,", "qua", "ante",
  "quam", "nati,", "et", "ad", "dolores", "ita", "paratus", "est,", "ut",
  "meminerit", "maximos", "morte", "finiri,", "parvos", "multa",
  "habere", "intervalla", "requietis,", "mediocrium", "nos", "esse",
  "dominos,", "ut,", "si", "tolerabiles", "sint,", "feramus,", "si",
  "minus,", "animo", "aequo", "e", "vita,", "cum", "ea", "non",
  "placeat,", "tamquam", "e", "theatro", "exeamus", "quibus", "rebus",
  "intellegitur", "nec", "timiditatem", "ignaviamque", "vituperari",
  "nec", "fortitudinem", "patientiamque", "laudari", "suo", "nomine,",
  "sed", "illas", "reici,", "quia", "dolorem", "pariant,", "has",
  "optari,", "quia", "voluptatem", "iustitia", "restat,", "ut", "de",
  "omni", "virtute", "sit", "dictum", "sed", "similia", "fere", "dici",
  "possunt", "ut", "enim", "sapientiam,", "temperantiam,",
  "fortitudinem", "copulatas", "esse", "docui", "cum", "voluptate,",
  "ut", "ab", "ea", "nullo", "modo", "nec", "divelli", "nec", "distrahi",
  "possint,", "sic", "de", "iustitia", "iudicandum", "est,", "quae",
  "non", "modo", "numquam", "nocet", "cuiquam,", "sed", "contra",
  "semper", "afficit", "cum", "vi", "sua", "atque", "natura,", "quod",
  "tranquillat", "animos,", "tum", "spe", "nihil", "earum", "rerum",
  "defuturum,", "quas", "natura", "non", "depravata", "desiderat",
  "[et]", "quem", "ad", "modum", "temeritas", "et", "libido", "et",
  "ignavia", "semper", "animum", "excruciant", "et", "semper",
  "sollicitant", "turbulentaeque", "sunt,", "sic", "[inprobitas", "si]",
  "cuius", "in", "mente", "consedit,", "hoc", "ipso,", "quod", "adest,",
  "turbulenta", "est;", "si", "vero", "molita", "quippiam", "est,",
  "quamvis", "occulte", "fecerit,", "numquam", "tamen", "id", "confidet",
  "fore", "semper", "occultum", "plerumque", "improborum", "facta",
  "primo", "suspicio", "insequitur,", "dein", "sermo", "atque", "fama,",
  "tum", "accusator,", "tum", "iudex;", "multi", "etiam,", "ut", "te",
  "consule,", "ipsi", "se", "indicaverunt", "quodsi", "qui", "satis",
  "sibi", "contra", "hominum", "conscientiam", "saepti", "esse", "et",
  "muniti", "videntur,", "deorum", "tamen", "horrent", "easque", "ipsas",
  "sollicitudines,", "quibus", "eorum", "animi", "noctesque", "diesque",
  "exeduntur,", "a", "diis", "inmortalibus", "supplicii", "causa",
  "importari", "putant", "quae", "autem", "tanta", "ex", "improbis",
  "factis", "ad", "minuendas", "vitae", "molestias", "accessio",
  "potest", "fieri,", "quanta", "ad", "augendas,", "cum", "conscientia",
  "factorum,", "tum", "poena", "legum", "odioque", "civium?", "et",
  "tamen", "in", "quibusdam", "neque", "pecuniae", "modus", "est",
  "neque", "honoris", "neque", "imperii", "nec", "libidinum", "nec",
  "epularum", "nec", "reliquarum", "cupiditatum,", "quas", "nulla",
  "praeda", "umquam", "improbe", "parta", "minuit,", "[sed]", "potius",
  "inflammat,", "ut", "coercendi", "magis", "quam", "dedocendi", "esse",
  "videantur", "invitat", "igitur", "vera", "ratio", "bene", "sanos",
  "ad", "iustitiam,", "aequitatem,", "fidem,", "neque", "homini",
  "infanti", "aut", "inpotenti", "iniuste", "facta", "conducunt,", "qui",
  "nec", "facile", "efficere", "possit,", "quod", "conetur,", "nec",
  "optinere,", "si", "effecerit,", "et", "opes", "vel", "fortunae",
  "vel", "ingenii", "liberalitati", "magis", "conveniunt,", "qua", "qui",
  "utuntur,", "benivolentiam", "sibi", "conciliant", "et,", "quod",
  "aptissimum", "est", "ad", "quiete", "vivendum,", "caritatem,",
  "praesertim", "cum", "omnino", "nulla", "sit", "causa", "peccandi",
  "quae", "enim", "cupiditates", "a", "natura", "proficiscuntur,",
  "facile", "explentur", "sine", "ulla", "iniuria,", "quae", "autem",
  "inanes", "sunt,", "iis", "parendum", "non", "est", "nihil", "enim",
  "desiderabile", "concupiscunt,", "plusque", "in", "ipsa", "iniuria",
  "detrimenti", "est", "quam", "in", "iis", "rebus", "emolumenti,",
  "quae", "pariuntur", "iniuria", "itaque", "ne", "iustitiam", "quidem",
  "recte", "quis", "dixerit", "per", "se", "ipsam", "optabilem,", "sed",
  "quia", "iucunditatis", "vel", "plurimum", "afferat", "nam", "diligi",
  "et", "carum", "esse", "iucundum", "est", "propterea,", "quia",
  "tutiorem", "vitam", "et", "voluptatem", "pleniorem", "efficit",
  "itaque", "non", "ob", "ea", "solum", "incommoda,", "quae", "eveniunt",
  "inprobis,", "fugiendam", "inprobitatem", "putamus,", "sed", "multo",
  "etiam", "magis,", "quod,", "cuius", "in", "animo", "versatur,",
  "numquam", "sinit", "eum", "respirare,", "numquam", "adquiescere",
  "quodsi", "ne", "ipsarum", "quidem", "virtutum", "laus,", "in", "qua",
  "maxime", "ceterorum", "philosophorum", "exultat", "oratio,",
  "reperire", "exitum", "potest,", "nisi", "derigatur", "ad",
  "voluptatem,", "voluptas", "autem", "est", "sola,", "quae", "nos",
  "vocet", "ad", "se", "et", "alliciat", "suapte", "natura,", "non",
  "potest", "esse", "dubium,", "quin", "id", "sit", "summum", "atque",
  "extremum", "bonorum", "omnium,", "beateque", "vivere", "nihil",
  "aliud", "sit", "nisi", "cum", "voluptate", "vivere", "huic",
  "certae", "stabilique", "sententiae", "quae", "sint", "coniuncta",
  "explicabo", "brevi", "nullus", "in", "ipsis", "error", "est",
  "finibus", "bonorum", "et", "malorum,", "id", "est", "in", "voluptate",
  "aut", "in", "dolore,", "sed", "in", "his", "rebus", "peccant,", "cum",
  "e", "quibus", "haec", "efficiantur", "ignorant", "animi", "autem",
  "voluptates", "et", "dolores", "nasci", "fatemur", "e", "corporis",
  "voluptatibus", "et", "doloribus", "itaque", "concedo,", "quod",
  "modo", "dicebas,", "cadere", "causa,", "si", "qui", "e", "nostris",
  "aliter", "existimant,", "quos", "quidem", "video", "esse", "multos,",
  "sed", "imperitos", "quamquam", "autem", "et", "laetitiam",
  "nobis", "voluptas", "animi", "et", "molestiam", "dolor", "afferat,",
  "eorum", "tamen", "utrumque", "et", "ortum", "esse", "e", "corpore",
  "et", "ad", "corpus", "referri,", "nec", "ob", "eam", "causam", "non",
  "multo", "maiores", "esse", "et", "voluptates", "et", "dolores",
  "animi", "quam", "corporis", "nam", "corpore", "nihil", "nisi",
  "praesens", "et", "quod", "adest", "sentire", "possumus,", "animo",
  "autem", "et", "praeterita", "et", "futura", "ut", "enim", "aeque",
  "doleamus", "animo,", "cum", "corpore", "dolemus,", "fieri", "tamen",
  "permagna", "accessio", "potest,", "si", "aliquod", "aeternum", "et",
  "infinitum", "impendere", "malum", "nobis", "opinemur", "quod",
  "idem", "licet", "transferre", "in", "voluptatem,", "ut", "ea",
  "maior", "sit,", "si", "nihil", "tale", "metuamus", "iam", "illud",
  "quidem", "perspicuum", "est,", "maximam", "animi", "aut",
  "voluptatem", "aut", "molestiam", "plus", "aut", "ad", "beatam", "aut",
  "ad", "miseram", "vitam", "afferre", "momenti", "quam", "eorum",
  "utrumvis,", "si", "aeque", "diu", "sit", "in", "corpore", "non",
  "placet", "autem", "detracta", "voluptate", "aegritudinem", "statim",
  "consequi,", "nisi", "in", "voluptatis", "locum", "dolor", "forte",
  "successerit,", "at", "contra", "gaudere", "nosmet", "omittendis",
  "doloribus,", "etiamsi", "voluptas", "ea,", "quae", "sensum",
  "moveat,", "nulla", "successerit,", "eoque", "intellegi", "potest",
  "quanta", "voluptas", "sit", "non", "dolere", "sed", "ut", "iis",
  "bonis", "erigimur,", "quae", "expectamus,", "sic", "laetamur", "iis,",
  "quae", "recordamur", "stulti", "autem", "malorum", "memoria",
  "torquentur,", "sapientes", "bona", "praeterita", "grata",
  "recordatione", "renovata", "delectant", "est", "autem", "situm",
  "in", "nobis", "ut", "et", "adversa", "quasi", "perpetua", "oblivione",
  "obruamus", "et", "secunda", "iucunde", "ac", "suaviter",
  "meminerimus", "sed", "cum", "ea,", "quae", "praeterierunt,", "acri",
  "animo", "et", "attento", "intuemur,", "tum", "fit", "ut", "aegritudo",
  "sequatur,", "si", "illa", "mala", "sint,", "laetitia,", "si", "bona",
  "o", "praeclaram", "beate", "vivendi", "et", "apertam", "et",
  "simplicem", "et", "directam", "viam!", "cum", "enim", "certe",
  "nihil", "homini", "possit", "melius", "esse", "quam", "vacare",
  "omni", "dolore", "et", "molestia", "perfruique", "maximis", "et",
  "animi", "et", "corporis", "voluptatibus,", "videtisne", "quam",
  "nihil", "praetermittatur", "quod", "vitam", "adiuvet,", "quo",
  "facilius", "id,", "quod", "propositum", "est,", "summum", "bonum",
  "consequamur?", "clamat", "epicurus,", "is", "quem", "vos", "nimis",
  "voluptatibus", "esse", "deditum", "dicitis;", "non", "posse",
  "iucunde", "vivi,", "nisi", "sapienter,", "honeste", "iusteque",
  "vivatur,", "nec", "sapienter,", "honeste,", "iuste,", "nisi",
  "iucunde", "neque", "enim", "civitas", "in", "seditione", "beata",
  "esse", "potest", "nec", "in", "discordia", "dominorum", "domus;",
  "quo", "minus", "animus", "a", "se", "ipse", "dissidens", "secumque",
  "discordans", "gustare", "partem", "ullam", "liquidae", "voluptatis",
  "et", "liberae", "potest", "atqui", "pugnantibus", "et", "contrariis",
  "studiis", "consiliisque", "semper", "utens", "nihil", "quieti",
  "videre,", "nihil", "tranquilli", "potest", "quodsi", "corporis",
  "gravioribus", "morbis", "vitae", "iucunditas", "impeditur,", "quanto",
  "magis", "animi", "morbis", "impediri", "necesse", "est!", "animi",
  "autem", "morbi", "sunt", "cupiditates", "inmensae", "et", "inanes",
  "divitiarum,", "gloriae,", "dominationis,", "libidinosarum", "etiam",
  "voluptatum", "accedunt", "aegritudines,", "molestiae,", "maerores,",
  "qui", "exedunt", "animos", "conficiuntque", "curis", "hominum", "non",
  "intellegentium", "nihil", "dolendum", "esse", "animo,", "quod", "sit",
  "a", "dolore", "corporis", "praesenti", "futurove", "seiunctum",
  "nec", "vero", "quisquam", "stultus", "non", "horum", "morborum",
  "aliquo", "laborat,", "nemo", "igitur", "est", "non", "miser",
  "accedit", "etiam", "mors,", "quae", "quasi", "saxum", "tantalo",
  "semper", "impendet,", "tum", "superstitio,", "qua", "qui", "est",
  "imbutus", "quietus", "esse", "numquam", "potest", "praeterea",
  "bona", "praeterita", "non", "meminerunt,", "praesentibus", "non",
  "fruuntur,", "futura", "modo", "expectant,", "quae", "quia", "certa",
  "esse", "non", "possunt,", "conficiuntur", "et", "angore", "et",
  "metu", "maximeque", "cruciantur,", "cum", "sero", "sentiunt",
  "frustra", "se", "aut", "pecuniae", "studuisse", "aut", "imperiis",
  "aut", "opibus", "aut", "gloriae", "nullas", "enim", "consequuntur",
  "voluptates,", "quarum", "potiendi", "spe", "inflammati", "multos",
  "labores", "magnosque", "susceperant", "ecce", "autem", "alii",
  "minuti", "et", "angusti", "aut", "omnia", "semper", "desperantes",
  "aut", "malivoli,", "invidi,", "difficiles,", "lucifugi,", "maledici,",
  "monstruosi,", "alii", "autem", "etiam", "amatoriis", "levitatibus",
  "dediti,", "alii", "petulantes,", "alii", "audaces,", "protervi,",
  "idem", "intemperantes", "et", "ignavi,", "numquam", "in", "sententia",
  "permanentes,", "quas", "ob", "causas", "in", "eorum", "vita", "nulla",
  "est", "intercapedo", "molestiae", "igitur", "neque", "stultorum",
  "quisquam", "beatus", "neque", "sapientium", "non", "beatus",
  "multoque", "hoc", "melius", "nos", "veriusque", "quam", "stoici",
  "illi", "enim", "negant", "esse", "bonum", "quicquam", "nisi",
  "nescio", "quam", "illam", "umbram,", "quod", "appellant", "honestum",
  "non", "tam", "solido", "quam", "splendido", "nomine,", "virtutem",
  "autem", "nixam", "hoc", "honesto", "nullam", "requirere",
  "voluptatem", "atque", "ad", "beate", "vivendum", "se", "ipsa", "esse",
  "contentam", "sed", "possunt", "haec", "quadam", "ratione", "dici",
  "non", "modo", "non", "repugnantibus,", "verum", "etiam",
  "approbantibus", "nobis", "sic", "enim", "ab", "epicuro", "sapiens",
  "semper", "beatus", "inducitur:", "finitas", "habet", "cupiditates,",
  "neglegit", "mortem,", "de", "diis", "inmortalibus", "sine", "ullo",
  "metu", "vera", "sentit,", "non", "dubitat,", "si", "ita", "melius",
  "sit,", "migrare", "de", "vita", "his", "rebus", "instructus",
  "semper", "est", "in", "voluptate", "neque", "enim", "tempus", "est",
  "ullum,", "quo", "non", "plus", "voluptatum", "habeat", "quam",
  "dolorum", "nam", "et", "praeterita", "grate", "meminit", "et",
  "praesentibus", "ita", "potitur,", "ut", "animadvertat", "quanta",
  "sint", "ea", "quamque", "iucunda,", "neque", "pendet", "ex",
  "futuris,", "sed", "expectat", "illa,", "fruitur", "praesentibus",
  "ab", "iisque", "vitiis,", "quae", "paulo", "ante", "collegi,",
  "abest", "plurimum", "et,", "cum", "stultorum", "vitam", "cum", "sua",
  "comparat,", "magna", "afficitur", "voluptate", "dolores", "autem",
  "si", "qui", "incurrunt,", "numquam", "vim", "tantam", "habent,", "ut",
  "non", "plus", "habeat", "sapiens,", "quod", "gaudeat,", "quam",
  "quod", "angatur", "optime", "vero", "epicurus,", "quod", "exiguam",
  "dixit", "fortunam", "intervenire", "sapienti", "maximasque", "ab",
  "eo", "et", "gravissimas", "res", "consilio", "ipsius", "et",
  "ratione", "administrari", "neque", "maiorem", "voluptatem", "ex",
  "infinito", "tempore", "aetatis", "percipi", "posse,", "quam", "ex",
  "hoc", "percipiatur,", "quod", "videamus", "esse", "finitum", "in",
  "dialectica", "autem", "vestra", "nullam", "existimavit", "esse",
  "nec", "ad", "melius", "vivendum", "nec", "ad", "commodius",
  "disserendum", "viam", "in", "physicis", "plurimum", "posuit", "ea",
  "scientia", "et", "verborum", "vis", "et", "natura", "orationis", "et",
  "consequentium", "repugnantiumve", "ratio", "potest", "perspici",
  "omnium", "autem", "rerum", "natura", "cognita", "levamur",
  "superstitione,", "liberamur", "mortis", "metu,", "non", "conturbamur",
  "ignoratione", "rerum,", "e", "qua", "ipsa", "horribiles", "existunt",
  "saepe", "formidines", "denique", "etiam", "morati", "melius",
  "erimus,", "cum", "didicerimus", "quid", "natura", "desideret", "tum",
  "vero,", "si", "stabilem", "scientiam", "rerum", "tenebimus,",
  "servata", "illa,", "quae", "quasi", "delapsa", "de", "caelo", "est",
  "ad", "cognitionem", "omnium,", "regula,", "ad", "quam", "omnia",
  "iudicia", "rerum", "dirigentur,", "numquam", "ullius", "oratione",
  "victi", "sententia", "desistemus", "nisi", "autem", "rerum",
  "natura", "perspecta", "erit,", "nullo", "modo", "poterimus",
  "sensuum", "iudicia", "defendere", "quicquid", "porro", "animo",
  "cernimus,", "id", "omne", "oritur", "a", "sensibus;", "qui", "si",
  "omnes", "veri", "erunt,", "ut", "epicuri", "ratio", "docet,", "tum",
  "denique", "poterit", "aliquid", "cognosci", "et", "percipi", "quos",
  "qui", "tollunt", "et", "nihil", "posse", "percipi", "dicunt,", "ii",
  "remotis", "sensibus", "ne", "id", "ipsum", "quidem", "expedire",
  "possunt,", "quod", "disserunt", "praeterea", "sublata", "cognitione",
  "et", "scientia", "tollitur", "omnis", "ratio", "et", "vitae",
  "degendae", "et", "rerum", "gerendarum", "sic", "e", "physicis", "et",
  "fortitudo", "sumitur", "contra", "mortis", "timorem", "et",
  "constantia", "contra", "metum", "religionis", "et", "sedatio",
  "animi", "omnium", "rerum", "occultarum", "ignoratione", "sublata",
  "et", "moderatio", "natura", "cupiditatum", "generibusque", "earum",
  "explicatis,", "et,", "ut", "modo", "docui,", "cognitionis", "regula",
  "et", "iudicio", "ab", "eadem", "illa", "constituto", "veri", "a",
  "falso", "distinctio", "traditur", "restat", "locus", "huic",
  "disputationi", "vel", "maxime", "necessarius", "de", "amicitia,",
  "quam,", "si", "voluptas", "summum", "sit", "bonum,", "affirmatis",
  "nullam", "omnino", "fore", "de", "qua", "epicurus", "quidem", "ita",
  "dicit,", "omnium", "rerum,", "quas", "ad", "beate", "vivendum",
  "sapientia", "comparaverit,", "nihil", "esse", "maius", "amicitia,",
  "nihil", "uberius,", "nihil", "iucundius", "nec", "vero", "hoc",
  "oratione", "solum,", "sed", "multo", "magis", "vita", "et", "factis",
  "et", "moribus", "comprobavit", "quod", "quam", "magnum", "sit",
  "fictae", "veterum", "fabulae", "declarant,", "in", "quibus", "tam",
  "multis", "tamque", "variis", "ab", "ultima", "antiquitate",
  "repetitis", "tria", "vix", "amicorum", "paria", "reperiuntur,", "ut",
  "ad", "orestem", "pervenias", "profectus", "a", "theseo", "at",
  "vero", "epicurus", "una", "in", "domo,", "et", "ea", "quidem",
  "angusta,", "quam", "magnos", "quantaque", "amoris", "conspiratione",
  "consentientis", "tenuit", "amicorum", "greges!", "quod", "fit",
  "etiam", "nunc", "ab", "epicureis", "sed", "ad", "rem", "redeamus;",
  "de", "hominibus", "dici", "non", "necesse", "est", "tribus",
  "igitur", "modis", "video", "esse", "a", "nostris", "de", "amicitia",
  "disputatum", "alii", "cum", "eas", "voluptates,", "quae", "ad",
  "amicos", "pertinerent,", "negarent", "esse", "per", "se", "ipsas",
  "tam", "expetendas,", "quam", "nostras", "expeteremus,", "quo", "loco",
  "videtur", "quibusdam", "stabilitas", "amicitiae", "vacillare,",
  "tuentur", "tamen", "eum", "locum", "seque", "facile,", "ut", "mihi",
  "videtur,", "expediunt", "ut", "enim", "virtutes,", "de", "quibus",
  "ante", "dictum", "est,", "sic", "amicitiam", "negant", "posse", "a",
  "voluptate", "discedere", "nam", "cum", "solitudo", "et", "vita",
  "sine", "amicis", "insidiarum", "et", "metus", "plena", "sit,",
  "ratio", "ipsa", "monet", "amicitias", "comparare,", "quibus",
  "partis", "confirmatur", "animus", "et", "a", "spe", "pariendarum",
  "voluptatum", "seiungi", "non", "potest", "atque", "ut", "odia,",
  "invidiae,", "despicationes", "adversantur", "voluptatibus,", "sic",
  "amicitiae", "non", "modo", "fautrices", "fidelissimae,", "sed",
  "etiam", "effectrices", "sunt", "voluptatum", "tam", "amicis", "quam",
  "sibi,", "quibus", "non", "solum", "praesentibus", "fruuntur,", "sed",
  "etiam", "spe", "eriguntur", "consequentis", "ac", "posteri",
  "temporis", "quod", "quia", "nullo", "modo", "sine", "amicitia",
  "firmam", "et", "perpetuam", "iucunditatem", "vitae", "tenere",
  "possumus", "neque", "vero", "ipsam", "amicitiam", "tueri,", "nisi",
  "aeque", "amicos", "et", "nosmet", "ipsos", "diligamus,", "idcirco",
  "et", "hoc", "ipsum", "efficitur", "in", "amicitia,", "et", "amicitia",
  "cum", "voluptate", "conectitur", "nam", "et", "laetamur", "amicorum",
  "laetitia", "aeque", "atque", "nostra", "et", "pariter", "dolemus",
  "angoribus", "quocirca", "eodem", "modo", "sapiens", "erit",
  "affectus", "erga", "amicum,", "quo", "in", "se", "ipsum,", "quosque",
  "labores", "propter", "suam", "voluptatem", "susciperet,", "eosdem",
  "suscipiet", "propter", "amici", "voluptatem", "quaeque", "de",
  "virtutibus", "dicta", "sunt,", "quem", "ad", "modum", "eae", "semper",
  "voluptatibus", "inhaererent,", "eadem", "de", "amicitia", "dicenda",
  "sunt", "praeclare", "enim", "epicurus", "his", "paene", "verbis:",
  "'eadem',", "inquit,", "'scientia", "confirmavit", "animum,", "ne",
  "quod", "aut", "sempiternum", "aut", "diuturnum", "timeret", "malum,",
  "quae", "perspexit", "in", "hoc", "ipso", "vitae", "spatio",
  "amicitiae", "praesidium", "esse", "firmissimum'", "sunt", "autem",
  "quidam", "epicurei", "timidiores", "paulo", "contra", "vestra",
  "convicia,", "sed", "tamen", "satis", "acuti,", "qui", "verentur",
  "ne,", "si", "amicitiam", "propter", "nostram", "voluptatem",
  "expetendam", "putemus,", "tota", "amicitia", "quasi", "claudicare",
  "videatur", "itaque", "primos", "congressus", "copulationesque", "et",
  "consuetudinum", "instituendarum", "voluntates", "fieri", "propter",
  "voluptatem;", "cum", "autem", "usus", "progrediens", "familiaritatem",
  "effecerit,", "tum", "amorem", "efflorescere", "tantum,", "ut,",
  "etiamsi", "nulla", "sit", "utilitas", "ex", "amicitia,", "tamen",
  "ipsi", "amici", "propter", "se", "ipsos", "amentur", "etenim", "si",
  "loca,", "si", "fana,", "si", "urbes,", "si", "gymnasia,", "si",
  "campum,", "si", "canes,", "si", "equos,", "si", "ludicra",
  "exercendi", "aut", "venandi", "consuetudine", "adamare", "solemus,",
  "quanto", "id", "in", "hominum", "consuetudine", "facilius", "fieri",
  "poterit", "et", "iustius?", "sunt", "autem,", "qui", "dicant",
  "foedus", "esse", "quoddam", "sapientium,", "ut", "ne", "minus",
  "amicos", "quam", "se", "ipsos", "diligant", "quod", "et", "posse",
  "fieri", "intellegimus", "et", "saepe", "etiam", "videmus,", "et",
  "perspicuum", "est", "nihil", "ad", "iucunde", "vivendum", "reperiri",
  "posse,", "quod", "coniunctione", "tali", "sit", "aptius", "quibus",
  "ex", "omnibus", "iudicari", "potest", "non", "modo", "non",
  "impediri", "rationem", "amicitiae,", "si", "summum", "bonum", "in",
  "voluptate", "ponatur,", "sed", "sine", "hoc", "institutionem",
  "omnino", "amicitiae", "non", "posse", "reperiri", "quapropter", "si",
  "ea,", "quae", "dixi,", "sole", "ipso", "illustriora", "et",
  "clariora", "sunt,", "si", "omnia", "dixi", "hausta", "e", "fonte",
  "naturae,", "si", "tota", "oratio", "nostra", "omnem", "sibi", "fidem",
  "sensibus", "confirmat,", "id", "est", "incorruptis", "atque",
  "integris", "testibus,", "si", "infantes", "pueri,", "mutae", "etiam",
  "bestiae", "paene", "loquuntur", "magistra", "ac", "duce", "natura",
  "nihil", "esse", "prosperum", "nisi", "voluptatem,", "nihil",
  "asperum", "nisi", "dolorem,", "de", "quibus", "neque", "depravate",
  "iudicant", "neque", "corrupte,", "nonne", "ei", "maximam", "gratiam",
  "habere", "debemus,", "qui", "hac", "exaudita", "quasi", "voce",
  "naturae", "sic", "eam", "firme", "graviterque", "comprehenderit,",
  "ut", "omnes", "bene", "sanos", "in", "viam", "placatae,",
  "tranquillae,", "quietae,", "beatae", "vitae", "deduceret?", "qui",
  "quod", "tibi", "parum", "videtur", "eruditus,", "ea", "causa", "est,",
  "quod", "nullam", "eruditionem", "esse", "duxit,", "nisi", "quae",
  "beatae", "vitae", "disciplinam", "iuvaret", "an", "ille", "tempus",
  "aut", "in", "poetis", "evolvendis,", "ut", "ego", "et", "triarius",
  "te", "hortatore", "facimus,", "consumeret,", "in", "quibus", "nulla",
  "solida", "utilitas", "omnisque", "puerilis", "est", "delectatio,",
  "aut", "se,", "ut", "plato,", "in", "musicis,", "geometria,",
  "numeris,", "astris", "contereret,", "quae", "et", "a", "falsis",
  "initiis", "profecta", "vera", "esse", "non", "possunt", "et,", "si",
  "essent", "vera,", "nihil", "afferrent,", "quo", "iucundius,", "id",
  "est", "quo", "melius", "viveremus,", "eas", "ergo", "artes",
  "persequeretur,", "vivendi", "artem", "tantam", "tamque", "et",
  "operosam", "et", "perinde", "fructuosam", "relinqueret?", "non",
  "ergo", "epicurus", "ineruditus,", "sed", "ii", "indocti,", "qui,",
  "quae", "pueros", "non", "didicisse", "turpe", "est,", "ea", "putant",
  "usque", "ad", "senectutem", "esse", "discenda", "quae", "cum",
  "dixisset,", "explicavi,", "inquit,", "sententiam", "meam,", "et",
  "eo", "quidem", "consilio,", "tuum", "iudicium", "ut", "cognoscerem,",
  "quoniam", "mihi", "ea", "facultas,", "ut", "id", "meo", "arbitratu",
  "facerem,", "ante", "hoc", "tempus", "numquam", "est", "data"
};

#endif
